services:
  db:
      image: postgres:15-alpine
      container_name: db-bookmanager
      restart: always
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: SenhaSQL
        POSTGRES_DB: book_manager
      ports:
        - "5434:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin-bookmanager
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "5050:80" 
      depends_on:
        - db
  backend:
    build: ./BookManager.API
    container_name: api-bookmanager
    restart: on-failure
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5123
      - ConnectionStrings__AppDbConnectionString=Host=db;Database=book_manager;Username=admin;Password=SenhaSQL
      - Jwt__Key=minha-super-chave-secreta-para-token-jwt-2026
      - Jwt__Issuer=BookManagerAPI
      - Jwt__Audience=UsuariosBookManagerAPI
    ports:
      - "5123:5123"

volumes:
  postgres_data: